name: Node.js CI

on:
  push:
    branches: [ master ]

  pull_request:
    branches: [ master ]

  workflow_dispatch: {}

jobs:
  Job:
    name: Node.js
    uses: artusjs/github-actions/.github/workflows/node-test.yml@master
    with:
      os: 'ubuntu-latest, macos-latest, windows-latest'
      version: '14, 16, 18, 20'
